- name: "Add domain to nginx map"
  lineinfile:
    dest: "/etc/nginx/conf.d/www-{{ enviro }}.conf"
    line: "    {{ item }}    {{ backend }};"
    state: present
    insertafter: "## Upstream for {{ enviro }} ##"
  with_items:
    - "{{ domain }}"
  notify: nginx reload

- name: "Add cache domain to nginx map"
  lineinfile:
    dest: "/etc/nginx/conf.d/www-{{ enviro }}.conf"
    line: "    cache.{{ item }}    {{ backend }};"
    state: present
    insertafter: "## Upstream for {{ enviro }} ##"
  with_items:
    - "{{ domain }}"
  notify: nginx reload

- name: "Enable PML viewing for {{ enviro }} {{ backend }}"
  template: src=pimpmylog.json dest={{ wp_doc_root }}/admin/logs/config.user.d/{{ enviro }}-{{ backend }}.json
  with_items:
    - "{{ domain }}"
