- name: "Add domain to nginx map"
  lineinfile:
    dest: "/etc/nginx/conf.d/www-{{ enviro }}.conf"
    line: "    {{ item }}    {{ backend }};"
    state: present
    insertafter: "## Upstream for {{ enviro }} ##"
  with_items:
    - "{{ domain }}"
  notify: nginx reload

- name: "Add cache domain to nginx map"
  lineinfile:
    dest: "/etc/nginx/conf.d/www-{{ enviro }}.conf"
    line: "    cache.{{ item }}    {{ backend }};"
    state: present
    insertafter: "## Upstream for {{ enviro }} ##"
  with_items:
    - "{{ domain }}"
  notify: nginx reload
